In [1]:
import numpy
import pandas
import random

weather_data = pandas.read_csv('E:/Working/DataMining/beijing_17_18_meo.csv')
weather_data.describe()

,longitude,latitude,temperature,pressure,humidity,wind_direction,wind_speed
count,158047.000000,158047.000000,158047.000000,158047.000000,158047.000000,157813.000000,157813.000000
mean,116.395672,40.047275,38.182775,1026.798200,354.312894,35487.471178,96.933881
std,0.395223,0.264798,5030.694816,5025.748455,17423.723518,184454.823456,9748.857634
min,115.692222,39.718611,-21.300000,940.000000,4.000000,0.000000,0.000000
25%,116.194167,39.847500,2.500000,994.200000,27.000000,78.000000,0.900000
50%,116.290556,39.973889,13.800000,1005.600000,48.000000,190.000000,1.500000
75%,116.626944,40.223333,23.200000,1016.900000,73.000000,280.000000,2.500000
max,117.117778,40.658889,999999.000000,999999.000000,999999.000000,999999.000000,999999.000000

In [2]:
# miss some data in wind_direction and wind_speed
weather_data.isnull().any()

station_id        False
longitude         False
latitude          False
utc_time          False
temperature       False
pressure          False
humidity          False
wind_direction     True
wind_speed         True
weather           False
dtype: bool

In [3]:
# If the wind speed is less than 0.5m/s (nearly no wind), the value of the wind_direction is 999017.
weather_data.drop_duplicates()
weather_data = weather_data.fillna(999999)

print(weather_data.loc[weather_data['wind_speed'] > 15, 'wind_speed'].value_counts())

999999.0    249
15.4          1
Name: wind_speed, dtype: int64

In [4]:
def clean_direction(d):
    if d > 360:
        return random.randint(0, 360)
    else:
        return d

weather_data['wind_direction'] = weather_data.wind_direction.apply(clean_direction)

def clean_speed(s):
    if s > 16:
        return random.randint(0, 16)
    else:
        return s

weather_data['wind_speed'] = weather_data.wind_speed.apply(clean_speed)

def clean_temperature(t):
    if not (-20 <= t <= 40):
        return random.randint(-20, 40)
    else:
        return t

weather_data['temperature'] = weather_data.temperature.apply(clean_temperature)

def clean_pressure(p):
    if not (990 <= p <= 1040):
        return random.randint(990, 1040)
    else:
        return p

weather_data['pressure'] = weather_data.pressure.apply(clean_pressure)

def clean_humidity(h):
    if not (0 <= h <= 100):
        return random.randint(0, 100)
    else:
        return h

weather_data['humidity'] = weather_data.humidity.apply(clean_humidity)

weather_data.describe()

,longitude,latitude,temperature,pressure,humidity,wind_direction,wind_speed
count,158047.000000,158047.000000,158047.000000,158047.000000,158047.000000,158047.000000,158047.000000
mean,116.395672,40.047275,12.873915,1011.664287,50.620980,176.489538,1.894269
std,0.395223,0.264798,12.079457,11.578527,26.054258,106.265768,1.392580
min,115.692222,39.718611,-20.000000,990.000000,1.000000,0.000000,0.000000
25%,116.194167,39.847500,2.500000,1002.100000,27.000000,75.000000,0.900000
50%,116.290556,39.973889,13.800000,1011.300000,48.000000,184.000000,1.500000
75%,116.626944,40.223333,23.200000,1020.400000,73.000000,266.000000,2.500000
max,117.117778,40.658889,39.900000,1040.000000,100.000000,360.000000,16.000000

In [5]:
weather_data.to_csv('E:/Working/DataMining/beijing_17_18_meo_cleaned.csv', index=False)