In [1]:
import seaborn
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

In [12]:
data = pd.read_csv('C:/Users/PC/Desktop/London/London_historical_aqi_forecast_stations_20180331.csv')
data.dtypes

MeasurementDateGMT     object
station_id             object
PM2.5 (ug/m3)         float64
PM10 (ug/m3)          float64
NO2 (ug/m3)           float64
dtype: object

In [13]:
data.describe()

       PM2.5 (ug/m3)   PM10 (ug/m3)    NO2 (ug/m3)
count  122985.000000  127108.000000  116216.000000
mean       13.234925      21.013378      43.256648
std        11.102862      14.280799      28.549720
min       -10.500000     -11.800000      -4.700000
25%         6.400000      11.800000      21.600000
50%        10.200000      17.500000      37.800000
75%        16.400000      26.300000      58.400000
max       189.700000     667.100000     336.100000

In [14]:
data.isnull().any()

MeasurementDateGMT    False
station_id            False
PM2.5 (ug/m3)          True
PM10 (ug/m3)           True
NO2 (ug/m3)            True
dtype: bool

In [19]:
data = data.dropna(thresh=3)
data

       MeasurementDateGMT station_id  PM2.5 (ug/m3)  PM10 (ug/m3)  NO2 (ug/m3)
0           2017/1/1 0:00        CD1           40.0          44.4         36.6
1           2017/1/1 1:00        CD1           31.6          34.4         46.2
2           2017/1/1 2:00        CD1           24.7          28.1         38.3
3           2017/1/1 3:00        CD1           21.2          24.5         32.8
4           2017/1/1 4:00        CD1           24.9          23.0         28.1
5           2017/1/1 5:00        CD1           24.6          23.9         29.3
6           2017/1/1 6:00        CD1           23.9          22.0         28.8
7           2017/1/1 7:00        CD1           22.0          22.9         34.6
8           2017/1/1 8:00        CD1           19.0          20.1         44.6
9           2017/1/1 9:00        CD1           19.9          24.4         55.3
10         2017/1/1 10:00        CD1           16.6          17.5         46.4
11         2017/1/1 11:00        CD1           14.5          14.6         42.5
12         2017/1/1 12:00        CD1           11.0          13.9         44.5
13         2017/1/1 13:00        CD1           13.9          13.4         53.6
14         2017/1/1 14:00        CD1            8.3           8.6         61.4
15         2017/1/1 15:00        CD1            7.3           6.1         57.9
16         2017/1/1 16:00        CD1            4.9           6.1         46.0
17         2017/1/1 17:00        CD1            4.6           8.1         96.5
18         2017/1/1 18:00        CD1            8.3           7.3         64.2
19         2017/1/1 19:00        CD1            7.3           8.9         59.7
20         2017/1/1 20:00        CD1            7.8          11.3         61.3
21         2017/1/1 21:00        CD1           11.1           9.8         57.0
22         2017/1/1 22:00        CD1            7.1          13.0         50.9
23         2017/1/1 23:00        CD1            6.8          11.4         40.2
24          2017/1/2 0:00        CD1            6.2           7.3         33.9
25          2017/1/2 1:00        CD1            9.0           9.9         21.7
26          2017/1/2 2:00        CD1            8.2           6.4         19.5
27          2017/1/2 3:00        CD1            7.0           9.1         18.8
28          2017/1/2 4:00        CD1            6.7           8.6         19.7
29          2017/1/2 5:00        CD1            7.4          13.3         27.7
...                   ...        ...            ...           ...          ...
141630    2018/3/29 18:00        TH4            6.3          16.4         80.7
141631    2018/3/29 19:00        TH4            8.5          16.7         85.9
141632    2018/3/29 20:00        TH4            8.8          19.4         89.6
141633    2018/3/29 21:00        TH4            8.8          17.9         82.4
141634    2018/3/29 22:00        TH4            5.0          14.5         61.8
141635    2018/3/29 23:00        TH4            4.6          14.2         67.6
141636     2018/3/30 0:00        TH4            4.8          11.8         55.4
141637     2018/3/30 1:00        TH4            2.0          11.4         47.4
141638     2018/3/30 2:00        TH4            4.2          13.5         51.4
141639     2018/3/30 3:00        TH4            3.1          13.8         45.8
141640     2018/3/30 4:00        TH4            5.0          12.6         45.4
141641     2018/3/30 5:00        TH4            4.4          13.1         45.6
141642     2018/3/30 6:00        TH4            8.2          14.6         47.4
141643     2018/3/30 7:00        TH4            8.2          18.3         36.6
141644     2018/3/30 8:00        TH4            9.0          15.6         35.0
141645     2018/3/30 9:00        TH4            9.1          17.7         38.0
141646    2018/3/30 10:00        TH4           10.3          12.7         35.3
141647    2018/3/30 11:00        TH4           12.0          13.2         29.4
141648    2018/3/30 12:00        TH4            9.1          13.5         26.2
141649    2018/3/30 13:00        TH4            7.7          15.0         35.3
141650    2018/3/30 14:00        TH4            7.0          12.2         36.6
141651    2018/3/30 15:00        TH4            6.4          11.0         30.9
141652    2018/3/30 16:00        TH4            6.4          14.0         39.8
141653    2018/3/30 17:00        TH4           14.4          16.6         55.2
141654    2018/3/30 18:00        TH4           11.2          18.8         63.3
141655    2018/3/30 19:00        TH4            6.3          16.1         67.7
141656    2018/3/30 20:00        TH4            3.5          11.2         44.3
141657    2018/3/30 21:00        TH4            4.7          12.3         52.8
141658    2018/3/30 22:00        TH4            5.4          14.0         54.7
141659    2018/3/30 23:00        TH4            8.9          16.5         47.0

[136347 rows x 5 columns]

In [23]:
data[['PM2.5 (ug/m3)', 'PM10 (ug/m3)', 'NO2 (ug/m3)']] = data[['PM2.5 (ug/m3)', 'PM10 (ug/m3)', 'NO2 (ug/m3)']].fillna(data[['PM2.5 (ug/m3)', 'PM10 (ug/m3)', 'NO2 (ug/m3)']].mean())
# air_quality.describe()
data

e:\python3.6\lib\site-packages\pandas\core\frame.py:2540: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self[k1] = value[k2]

       MeasurementDateGMT station_id  PM2.5 (ug/m3)  PM10 (ug/m3)  NO2 (ug/m3)
0           2017/1/1 0:00        CD1           40.0          44.4         36.6
1           2017/1/1 1:00        CD1           31.6          34.4         46.2
2           2017/1/1 2:00        CD1           24.7          28.1         38.3
3           2017/1/1 3:00        CD1           21.2          24.5         32.8
4           2017/1/1 4:00        CD1           24.9          23.0         28.1
5           2017/1/1 5:00        CD1           24.6          23.9         29.3
6           2017/1/1 6:00        CD1           23.9          22.0         28.8
7           2017/1/1 7:00        CD1           22.0          22.9         34.6
8           2017/1/1 8:00        CD1           19.0          20.1         44.6
9           2017/1/1 9:00        CD1           19.9          24.4         55.3
10         2017/1/1 10:00        CD1           16.6          17.5         46.4
11         2017/1/1 11:00        CD1           14.5          14.6         42.5
12         2017/1/1 12:00        CD1           11.0          13.9         44.5
13         2017/1/1 13:00        CD1           13.9          13.4         53.6
14         2017/1/1 14:00        CD1            8.3           8.6         61.4
15         2017/1/1 15:00        CD1            7.3           6.1         57.9
16         2017/1/1 16:00        CD1            4.9           6.1         46.0
17         2017/1/1 17:00        CD1            4.6           8.1         96.5
18         2017/1/1 18:00        CD1            8.3           7.3         64.2
19         2017/1/1 19:00        CD1            7.3           8.9         59.7
20         2017/1/1 20:00        CD1            7.8          11.3         61.3
21         2017/1/1 21:00        CD1           11.1           9.8         57.0
22         2017/1/1 22:00        CD1            7.1          13.0         50.9
23         2017/1/1 23:00        CD1            6.8          11.4         40.2
24          2017/1/2 0:00        CD1            6.2           7.3         33.9
25          2017/1/2 1:00        CD1            9.0           9.9         21.7
26          2017/1/2 2:00        CD1            8.2           6.4         19.5
27          2017/1/2 3:00        CD1            7.0           9.1         18.8
28          2017/1/2 4:00        CD1            6.7           8.6         19.7
29          2017/1/2 5:00        CD1            7.4          13.3         27.7
...                   ...        ...            ...           ...          ...
141630    2018/3/29 18:00        TH4            6.3          16.4         80.7
141631    2018/3/29 19:00        TH4            8.5          16.7         85.9
141632    2018/3/29 20:00        TH4            8.8          19.4         89.6
141633    2018/3/29 21:00        TH4            8.8          17.9         82.4
141634    2018/3/29 22:00        TH4            5.0          14.5         61.8
141635    2018/3/29 23:00        TH4            4.6          14.2         67.6
141636     2018/3/30 0:00        TH4            4.8          11.8         55.4
141637     2018/3/30 1:00        TH4            2.0          11.4         47.4
141638     2018/3/30 2:00        TH4            4.2          13.5         51.4
141639     2018/3/30 3:00        TH4            3.1          13.8         45.8
141640     2018/3/30 4:00        TH4            5.0          12.6         45.4
141641     2018/3/30 5:00        TH4            4.4          13.1         45.6
141642     2018/3/30 6:00        TH4            8.2          14.6         47.4
141643     2018/3/30 7:00        TH4            8.2          18.3         36.6
141644     2018/3/30 8:00        TH4            9.0          15.6         35.0
141645     2018/3/30 9:00        TH4            9.1          17.7         38.0
141646    2018/3/30 10:00        TH4           10.3          12.7         35.3
141647    2018/3/30 11:00        TH4           12.0          13.2         29.4
141648    2018/3/30 12:00        TH4            9.1          13.5         26.2
141649    2018/3/30 13:00        TH4            7.7          15.0         35.3
141650    2018/3/30 14:00        TH4            7.0          12.2         36.6
141651    2018/3/30 15:00        TH4            6.4          11.0         30.9
141652    2018/3/30 16:00        TH4            6.4          14.0         39.8
141653    2018/3/30 17:00        TH4           14.4          16.6         55.2
141654    2018/3/30 18:00        TH4           11.2          18.8         63.3
141655    2018/3/30 19:00        TH4            6.3          16.1         67.7
141656    2018/3/30 20:00        TH4            3.5          11.2         44.3
141657    2018/3/30 21:00        TH4            4.7          12.3         52.8
141658    2018/3/30 22:00        TH4            5.4          14.0         54.7
141659    2018/3/30 23:00        TH4            8.9          16.5         47.0

[136347 rows x 5 columns]

In [24]:
data.to_csv('C:/Users/PC/Desktop/London/London_historical_aqi_forecast_stations_20180331_cleaned.csv', index=False)