In [1]:
import seaborn
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

In [2]:
air_quality = pd.read_csv('E:/Working/DataMining/beijing_17_18_aq.csv')
air_quality.dtypes

stationId     object
utc_time      object
PM2.5        float64
PM10         float64
NO2          float64
CO           float64
O3           float64
SO2          float64
dtype: object

In [3]:
air_quality.describe()

# the count values are different

,PM2.5,PM10,NO2,CO,O3,SO2
count,290621.000000,227747.000000,292359.000000,268197.000000,290589.000000,292462.000000
mean,58.785570,88.059259,45.792457,0.960677,55.692755,8.981003
std,66.113851,89.292875,32.065045,1.001856,53.821424,11.702594
min,2.000000,5.000000,1.000000,0.100000,1.000000,1.000000
25%,16.000000,37.000000,20.000000,0.400000,12.000000,2.000000
50%,39.000000,70.000000,39.000000,0.700000,45.000000,5.000000
75%,77.000000,113.000000,66.000000,1.200000,79.000000,11.000000
max,1004.000000,3000.000000,300.000000,15.000000,504.000000,307.000000

In [4]:
air_quality.isnull().any()

stationId    False
utc_time     False
PM2.5         True
PM10          True
NO2           True
CO            True
O3            True
SO2           True
dtype: bool

In [5]:
air_quality = air_quality.dropna(thresh=3)
# air_quality.dropna(how = 'all')
air_quality

,stationId,utc_time,PM2.5,PM10,NO2,CO,O3,SO2
0,aotizhongxin_aq,2017-01-01 14:00:00,453.0,467.0,156.0,7.2,3.0,9.0
1,aotizhongxin_aq,2017-01-01 15:00:00,417.0,443.0,143.0,6.8,2.0,8.0
2,aotizhongxin_aq,2017-01-01 16:00:00,395.0,467.0,141.0,6.9,3.0,8.0
3,aotizhongxin_aq,2017-01-01 17:00:00,420.0,484.0,139.0,7.4,3.0,9.0
4,aotizhongxin_aq,2017-01-01 18:00:00,453.0,520.0,157.0,7.6,4.0,9.0
5,aotizhongxin_aq,2017-01-01 19:00:00,429.0,NaN,141.0,6.5,3.0,9.0
6,aotizhongxin_aq,2017-01-01 20:00:00,211.0,NaN,110.0,3.3,NaN,11.0
7,aotizhongxin_aq,2017-01-01 21:00:00,116.0,NaN,87.0,2.2,4.0,13.0
8,aotizhongxin_aq,2017-01-01 22:00:00,51.0,NaN,58.0,1.3,26.0,14.0
9,aotizhongxin_aq,2017-01-01 23:00:00,38.0,NaN,55.0,1.1,28.0,14.0
10,aotizhongxin_aq,2017-01-02 00:00:00,21.0,NaN,40.0,0.7,42.0,16.0
11,aotizhongxin_aq,2017-01-02 01:00:00,16.0,NaN,40.0,0.8,44.0,18.0
12,aotizhongxin_aq,2017-01-02 02:00:00,23.0,NaN,42.0,0.7,45.0,17.0
13,aotizhongxin_aq,2017-01-02 03:00:00,18.0,NaN,30.0,0.6,59.0,14.0
14,aotizhongxin_aq,2017-01-02 04:00:00,58.0,247.0,76.0,2.4,46.0,12.0
15,aotizhongxin_aq,2017-01-02 05:00:00,176.0,NaN,99.0,0.3,42.0,17.0
16,aotizhongxin_aq,2017-01-02 06:00:00,109.0,211.0,86.0,2.6,58.0,14.0
17,aotizhongxin_aq,2017-01-02 07:00:00,267.0,NaN,125.0,4.2,53.0,19.0
18,aotizhongxin_aq,2017-01-02 08:00:00,260.0,NaN,115.0,3.9,56.0,18.0
19,aotizhongxin_aq,2017-01-02 09:00:00,212.0,NaN,112.0,3.6,50.0,14.0
20,aotizhongxin_aq,2017-01-02 10:00:00,183.0,NaN,111.0,0.3,33.0,14.0
21,aotizhongxin_aq,2017-01-02 11:00:00,136.0,NaN,89.0,2.3,41.0,14.0
22,aotizhongxin_aq,2017-01-02 12:00:00,137.0,NaN,89.0,2.2,35.0,13.0
23,aotizhongxin_aq,2017-01-02 13:00:00,125.0,NaN,90.0,2.1,28.0,13.0
24,aotizhongxin_aq,2017-01-02 14:00:00,153.0,NaN,108.0,2.5,13.0,14.0
25,aotizhongxin_aq,2017-01-02 15:00:00,165.0,NaN,126.0,3.1,2.0,14.0
26,aotizhongxin_aq,2017-01-02 16:00:00,225.0,NaN,148.0,4.9,4.0,23.0
27,aotizhongxin_aq,2017-01-02 17:00:00,275.0,NaN,158.0,6.4,7.0,28.0
28,aotizhongxin_aq,2017-01-02 18:00:00,293.0,NaN,155.0,6.4,5.0,17.0
29,aotizhongxin_aq,2017-01-02 19:00:00,293.0,NaN,153.0,6.2,5.0,16.0
...,...,...,...,...,...,...,...,...
309297,zhiwuyuan_aq,2017-11-22 21:00:00,3.0,6.0,2.0,0.1,55.0,2.0
309298,zhiwuyuan_aq,2017-11-22 22:00:00,7.0,NaN,2.0,0.2,54.0,2.0
309299,zhiwuyuan_aq,2017-11-22 23:00:00,3.0,6.0,6.0,0.2,44.0,2.0
309300,zhiwuyuan_aq,2017-11-23 00:00:00,13.0,NaN,6.0,0.2,43.0,2.0
309301,zhiwuyuan_aq,2017-11-23 01:00:00,6.0,23.0,24.0,0.4,25.0,2.0
309302,zhiwuyuan_aq,2017-11-23 02:00:00,19.0,NaN,24.0,0.4,35.0,2.0
309303,zhiwuyuan_aq,2017-11-23 03:00:00,3.0,NaN,10.0,0.2,54.0,2.0
309304,zhiwuyuan_aq,2017-11-23 04:00:00,9.0,NaN,11.0,0.2,60.0,2.0
309305,zhiwuyuan_aq,2017-11-23 05:00:00,11.0,NaN,13.0,0.3,53.0,2.0
309306,zhiwuyuan_aq,2017-11-23 06:00:00,9.0,NaN,8.0,0.2,59.0,4.0
309307,zhiwuyuan_aq,2017-11-23 07:00:00,4.0,NaN,8.0,0.3,57.0,6.0
309308,zhiwuyuan_aq,2017-11-23 08:00:00,8.0,53.0,9.0,0.3,56.0,5.0
309309,zhiwuyuan_aq,2017-11-23 09:00:00,3.0,57.0,4.0,0.2,63.0,2.0
309310,zhiwuyuan_aq,2017-11-23 10:00:00,3.0,32.0,3.0,0.2,63.0,2.0
309311,zhiwuyuan_aq,2017-11-23 11:00:00,5.0,33.0,2.0,0.2,62.0,2.0
309312,zhiwuyuan_aq,2017-11-23 12:00:00,5.0,20.0,2.0,0.2,61.0,2.0
309313,zhiwuyuan_aq,2017-11-23 13:00:00,10.0,21.0,2.0,0.2,59.0,2.0
309314,zhiwuyuan_aq,2017-11-23 14:00:00,7.0,NaN,2.0,0.2,58.0,2.0
309315,zhiwuyuan_aq,2017-11-23 15:00:00,7.0,11.0,2.0,0.2,58.0,2.0
309316,zhiwuyuan_aq,2017-11-23 16:00:00,7.0,NaN,2.0,0.2,57.0,2.0
309317,zhiwuyuan_aq,2017-11-23 17:00:00,6.0,9.0,2.0,0.2,57.0,2.0
309318,zhiwuyuan_aq,2017-11-23 18:00:00,9.0,NaN,2.0,0.2,57.0,2.0
309319,zhiwuyuan_aq,2017-11-23 19:00:00,3.0,6.0,2.0,0.2,56.0,2.0
309320,zhiwuyuan_aq,2017-11-23 20:00:00,5.0,7.0,2.0,0.2,56.0,2.0
309321,zhiwuyuan_aq,2017-11-23 21:00:00,5.0,NaN,2.0,0.2,54.0,2.0
309322,zhiwuyuan_aq,2017-11-23 22:00:00,8.0,NaN,3.0,0.2,49.0,2.0
309323,zhiwuyuan_aq,2017-11-23 23:00:00,3.0,6.0,2.0,0.2,52.0,2.0
309324,zhiwuyuan_aq,2017-11-24 00:00:00,3.0,13.0,7.0,0.2,43.0,2.0
309325,zhiwuyuan_aq,2017-11-24 01:00:00,19.0,20.0,19.0,0.3,28.0,2.0
309326,zhiwuyuan_aq,2017-11-24 02:00:00,9.0,21.0,27.0,0.4,28.0,2.0

In [6]:
na_area = air_quality[air_quality.isnull().values == True]
for i in na_area.columns[2:]:
    print(i, len(na_area[na_area[i].isnull() == True]))

PM2.5 7318
PM10 77830
NO2 5746
CO 36694
O3 8253
SO2 5652

In [7]:
# air_quality = air_quality.fillna(0)
# fill the NA with 0
# fill the NA with mean , 'PM10', 'NO2', 'CO', 'O3', 'SO2'
air_quality[['PM2.5', 'PM10', 'NO2', 'CO', 'O3', 'SO2']] = air_quality[['PM2.5', 'PM10', 'NO2', 'CO', 'O3', 'SO2']].fillna(air_quality[['PM2.5', 'PM10', 'NO2', 'CO', 'O3', 'SO2']].mean())
# air_quality.describe()
air_quality.head()

         stationId             utc_time  PM2.5   PM10    NO2   CO   O3  SO2
0  aotizhongxin_aq  2017-01-01 14:00:00  453.0  467.0  156.0  7.2  3.0  9.0
1  aotizhongxin_aq  2017-01-01 15:00:00  417.0  443.0  143.0  6.8  2.0  8.0
2  aotizhongxin_aq  2017-01-01 16:00:00  395.0  467.0  141.0  6.9  3.0  8.0
3  aotizhongxin_aq  2017-01-01 17:00:00  420.0  484.0  139.0  7.4  3.0  9.0
4  aotizhongxin_aq  2017-01-01 18:00:00  453.0  520.0  157.0  7.6  4.0  9.0

In [8]:
air_quality.to_csv('E:/Working/DataMining/beijing_17_18_aq_cleaned.csv', index=False)